CREATE TABLE `yh_platform_updprice` (
  `PH_KEY` varchar(20) NOT NULL COMMENT '主键',
  `SHEETID` varchar(20) DEFAULT NULL COMMENT '单据编号',
  `REFSHEETID` varchar(20) DEFAULT NULL COMMENT '调价单号',
  `REFSHEETTYPE` int(11) DEFAULT NULL COMMENT '取消单类型',
  `SHEETCANCELFLAG` varchar(20) DEFAULT NULL COMMENT '取消标志  （Y正常  ，N  取消）',
  `SHOPID` varchar(6) DEFAULT NULL COMMENT '调价店号',
  `CHANGEMODE` int(11) DEFAULT NULL COMMENT '调价模式：0永久调价，1促销调价',
  `STARTDATE` varchar(30) DEFAULT '' COMMENT '开始日期',
  `ENDDATE` varchar(30) DEFAULT '' COMMENT '结束日期',
  `NMPRICEFLAG` int(11) DEFAULT NULL COMMENT '调售价标志 0不调正常售价;1调正常售价（包括促销售价、促销包装售价）',
  `CHECKDATE` datetime DEFAULT NULL COMMENT '审核日期',
  `EXECUTETIME` datetime DEFAULT NULL COMMENT '执行时间',
  `NOTE` varchar(64) DEFAULT NULL COMMENT '备注',
  `ORDERFLAG` int(11) DEFAULT NULL COMMENT '调价优先级别',
  `STARTTIME` varchar(10) DEFAULT NULL COMMENT '开始时间',
  `ENDTIME` varchar(10) DEFAULT NULL COMMENT '结束时间',
  `DMSHEETID` varchar(20) DEFAULT NULL COMMENT 'DM促销单号',
  `ISEMPTY` int(11) DEFAULT NULL COMMENT '是否允许为空',
  `AREAID` varchar(20) DEFAULT NULL COMMENT '区域信息',
  `UPDTYPE` varchar(10) DEFAULT NULL COMMENT '"调价类型\n调价类型：001 DM调价002 竞争调价003 市调调价004 出清调价\n\n融通传输：以下两种促销类型不传，传空值：\n1001 促销商品清单\n0013低进价入库\n\n融通传输：以下五种促销类型需传：\n0001日期段促销\n0002时段促销\n0003限量促销\n0004超量促销\n0012以旧换新"',
  `PLANID` varchar(10) DEFAULT NULL COMMENT '档期编号',
  `PROMNO` varchar(10) DEFAULT NULL COMMENT '促销号',
  `POPLEVEL` varchar(10) DEFAULT NULL COMMENT '(营销上线增加)促销级别   0：单品、1：组别、2：组站',
  `RULENO` varchar(30) NOT NULL COMMENT '(营销上线增加)活动号  ，所有单据不重复  按照这个单处理优先级',
  `FDMODE` varchar(4) DEFAULT NULL COMMENT '(营销上线增加)促销扣款分担方式1-进价差2-售价差'',',
  `SDFLAG` varchar(4) DEFAULT NULL COMMENT '(营销上线增加)时段标志(1-全天2-时段)',
  `CUSTTYPE` varchar(10) DEFAULT NULL COMMENT '(营销上线增加)会员类型'',',
  `PRI` int(11) DEFAULT NULL,
  `SYNCHRO` int(4) DEFAULT 0 COMMENT '同步标记：1 已同步 ，0 未同步',
  PRIMARY KEY (`PH_KEY`),
  UNIQUE KEY `UK_RULENO` (`RULENO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `yh_platform_updpriceitem` (
  `PH_KEY` varchar(20) NOT NULL COMMENT '主键',
  `SHEETID` varchar(20) DEFAULT NULL COMMENT '单据编号',
  `SEQID` int(11) DEFAULT NULL COMMENT '序号',
  `GOODSID` int(11) DEFAULT NULL,
  `VENDERID` varchar(10) DEFAULT NULL COMMENT '供应商编码(不为空时销售后计算供应商折让承担金额)',
  `ALLOCATERATE` decimal(7,4) DEFAULT NULL COMMENT '促销折让金额供应商分摊率（0..00～100.00％）',
  `OLDCOST` decimal(16,8) DEFAULT NULL COMMENT '原进价',
  `NEWCOST` decimal(16,8) DEFAULT NULL COMMENT '促销进价',
  `OLDPRICE` decimal(10,2) DEFAULT NULL COMMENT '原售价',
  `NEWPRICE` decimal(10,2) DEFAULT NULL COMMENT '新售价',
  `LIMITFLAG` int(11) DEFAULT NULL COMMENT '限量标志(1=定量)',
  `LIMITQTY` int(11) DEFAULT NULL COMMENT '限量销售量',
  `PROMFUND` decimal(12,3) DEFAULT NULL COMMENT '"促销基金\n融通传输：以下四种促销方式需传：\n0001日期段促销\n0002时段促销\n0003限量促销\n0004超量促销\n\n融通传输：以下三种促销类型传0值\n1001促销商品清单\n0012以旧换新\n0013低进价入库"',
  `DMFLAG` varchar(2) DEFAULT NULL COMMENT '是否DM促销',
  `ISPROMFLAG` int(11) DEFAULT NULL COMMENT '促销标识',
  `PRCMODE` varchar(1) DEFAULT NULL COMMENT '(营销上线增加)折扣形式   1、指定成交价；2、指定折扣率；3、指定减金额',
  `DISRATE` decimal(16,4) DEFAULT NULL COMMENT '(营销上线增加)折扣率',
  `DISAMT` decimal(16,4) DEFAULT NULL COMMENT '(营销上线增加)减价金额',
  `POPSETMODEL` varchar(10) DEFAULT NULL COMMENT '(营销上线增加)设置方式   1 商品 ，2 组合（品类+品牌）  ，3 供应商',
  `CATCODE` varchar(30) DEFAULT NULL COMMENT '(营销上线增加)设置品类',
  `PPCODE` varchar(30) DEFAULT NULL COMMENT '(营销上线增加)设置品牌',
  `SUPID` varchar(30) DEFAULT NULL COMMENT '(营销上线增加)设置供应商',
  `CANCELFLAG` varchar(10) DEFAULT NULL COMMENT '(营销上线增加)取消标识。',
  `POPJOINMODEL` varchar(10) DEFAULT NULL COMMENT '(营销上线增加)参与模式',
  PRIMARY KEY (`PH_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

