spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yidiandian.entity

